version: v0.12.0

dsn: postgres://kratos:secret@kratos-db:5432/kratos?sslmode=disable

serve:
  public:
    base_url: http://kratos:4433/
    cors:
      enabled: true
      allowed_origins:
        - "*"
      allowed_methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Content-Type
        - Cookie
      exposed_headers:
        - Set-Cookie
      allow_credentials: true

  admin:
    base_url: http://kratos:4434/

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.default.schema.json

selfservice:
  default_browser_return_url: http://nestjs:3000
  flows:
    login:
      ui_url: http://nestjs:3000/auth/login    # NestJS UI endpoint
      lifespan: 10m
    registration:
      ui_url: http://nestjs:3000/auth/register # NestJS UI endpoint
      lifespan: 10m
      after:
        password:
          hooks:
            - hook: session
    logout:
      after:
        default_browser_return_url: http://nestjs:3000/auth/logout-success
  methods:
    password:
      enabled: true
    oidc:
      enabled: false

session:
  lifespan: 768h
  cookie:
    domain: localhost
    same_site: Lax
    path: /

log:
  level: debug
